# Generated by Django 3.2.5 on 2021-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='data',
            field=models.CharField(max_length=10),
        ),
    ]
