# Generated by Django 3.2.5 on 2021-07-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyFlow', '0002_alter_produs_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produs',
            name='data',
            field=models.DateField(),
        ),
    ]
